version: 2
jobs:
  build:
    docker:
      -
        image: circleci/ruby:2.6.6
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
      -
        image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: playground_test

    steps:
      - checkout

      # bundler
      -
        type: cache-restore
        key: bundle-{{ checksum "Gemfile.lock" }}
      -
        run: gem install bundler --version "$BUNDLER_VERSION"
      -
        run: bundle check || bundle install
      -
        type: cache-save
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # postgres
      -
        run: dockerize -wait tcp://localhost:5432

      # database
      -
        run: bundle exec rake db:create db:schema:load

      # rubocop
      -
        type: shell
        command: bundle exec rubocop --format progress --format html --out tmp/rubocop.html

      # brakeman
      -
        type: shell
        command: bundle exec brakeman -z --format html --output tmp/brakeman.html

      # rspec
      -
        type: shell
        command: bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec/rspec.xml

      # results
      -
        type: test-results-store
        path: tmp/rspec

      # artifacts
      -
        type: artifacts-store
        path: coverage
        destination: coverage

      # artifacts
      -
        type: artifacts-store
        path: tmp/rubocop.html
        destination: rubocop.html

      # artifacts
      -
        type: artifacts-store
        path: tmp/brakeman.html
        destination: brakeman.html
